import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });
//
// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="robots" content="index, follow" />
        <meta name="googlebot" content="index, follow" />
        <meta name="description" content="Anny — Chin Chin, Singer, and Talent Coach. Book catering, live performances, and coaching. Modern, creative, and professional." />
        <meta property="og:title" content="Anny — Chin Chin, Singer, Talent Coach" />
        <meta property="og:description" content="Book premium Chin Chin catering, soulful music, and talent coaching with Anny. Modern, creative, and professional." />
        <meta property="og:type" content="website" />
        <meta property="og:url" content="https://your-domain.com/" />
        <meta property="og:image" content="https://your-domain.com/og-image.jpg" />
        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:title" content="Anny — Chin Chin, Singer, Talent Coach" />
        <meta name="twitter:description" content="Book premium Chin Chin catering, soulful music, and talent coaching with Anny." />
        <meta name="twitter:image" content="https://your-domain.com/og-image.jpg" />
      </head>
      <body
        className={`antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
